language: python

python:
  - 2.7

env:
  - DJANGO=1.9
  - DJANGO=1.10

install:
  - pip install django-fake-model
  - pip install coveralls

script:
  - python setup.py test
  - coverage run --source=mqueue setup.py test

after_success:
  coveralls
