language: python

python:
  - 2.7

env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10

install:
  - pip install django-fake-model
  - pip install pytest>=2.9 pytest-cov pytest-django coveralls

script:
  py.test mqueue/tests.py --cov=mqueue mqueue

after_success:
  coveralls
